databases:
  - name: contactdb
    plan: free
    databaseName: contacts_db
    user: contacthub_user

services:
  - type: web
    plan: free
    name: contacthub
    runtime: python
    rootDir: ContactHub/htmx-contacthub
    buildCommand: 'pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate'
    startCommand: 'gunicorn contacthub.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contactdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.11'
      - key: DEBUG
        value: 'False'
